arch:
  - amd64
  - ppc64le
language: c
sudo: required
services:
  - docker

env:
  - TAG=4.04
  - TAG=4.05
  - TAG=4.06
  - TAG=4.07
  - TAG=4.08

script:
  - docker build --build-arg tag=$TAG --tag colisanr/morsmall:$TRAVIS_BRANCH .
  - docker run --entrypoint /bin/sh colisanr/morsmall:$TRAVIS_BRANCH -c 'eval $(opam env) && cd /home/opam/morsmall && make install && make uninstall'
